define({
  root: ({
    labelDelete: "Delete",
	labelLoad: "Load", 
	labelSave: "Save", 
	labelRestore: "Restore", 
    errorNameExist: "Mapstate exists!",
    errorNameEmpty: "No map state found for %mapName%",
	errSaveFailure: "Failed to save the current map status", 
	errLoadFailure: "Failed to load the saved map status", 
	errDeleteFailure: "Failed to delete the saved map status", 
	msgSaveSuccess: "Map state saved for %mapName%", 
	msgStateStatus: "Last Map state saved on %date%", 
	msgLoadSuccess: "Map state loaded for %mapName%", 
	msgDeleteSuccess: "Map state deleted for %mapName%", 
    _widgetLabel: "Map State"
  }),
  "ar": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "it": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});